#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-25 14:30:36.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("finding_timestampColumns() works", {

  expect_error(
    kwb.misa:::finding_timestampColumns()
    # argument "dataFrame" is missing, with no default
  )

})

