#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mzamzo on 2021-11-25 14:30:34.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("yearly_crit_Events() works", {

  expect_error(
    kwb.misa:::yearly_crit_Events()
    # argument "dataFrame" is missing, with no default
  )

})

